### ISSUE TITLE
Slider doesn't work on `about:home` (and doesn't explain what's going wrong)

### ISSUE THREAD

**Issue by dholbert** [denschub/chrome-mask#23]
STR:
1. Install Chrome Mask.
2. Open a new tab page (for example, suppose you just restarted Firefox and now want to try out the extension, and Firefox is showing you a new-tab page because you just restarted).
3. Click the Chrome Mask toolbar button, and click its slider to try masking as Chrome.

ACTUAL RESULTS:
Slider looks like it glitches on for an instant and then snaps off again.  No clear explanation about what's going wrong.

EXPECTED RESULTS:
The extension should detect that this is a page where we can't mask, and ideally the slider should be disabled so it's not even available to click.

**Comment by dholbert** [comment]
This affects all `about:` pages, I think -- e.g. `about:about`.  It also affects our presentation of raster images like https://assets-prod.sumo.prod.webservices.mozgcp.net/media/uploads/products/2020-04-14-08-36-13-8dda6f.png

Though probably new-tab page is the page where users are most likely to inadvertently trigger this, e.g. when trying to activate the extension before navigating to a site.

**Comment by dholbert** [comment]
[Screencast of bug](https://github.com/user-attachments/assets/675e70f5-1ee5-46e3-850f-5700658d355f)

**Comment by denschub** [comment]
Ah yes, WebExtensions are not allowed on the `about:` scheme and the `moz-extension:` scheme. In the case of `about:` pages, [this matches](https://github.com/denschub/chrome-mask/blob/ab478d2929b3e70f2e844351c957b0e66fd59ade/src/popup.js#L60-L65) because `URL()` can't extract the hostname from an `about:` URL. In case of `moz-extension://`, this would pass, but it would do nothing.

Easy to handle this in the UI though. Thanks for the thorough report! <3

**Comment by denschub** [comment]
Fixed by #30.
